### ISSUE TITLE
dlopen error undefined symbol: DataLoader_ReadAll in libvgm.so

### ISSUE THREAD

**Issue by dreams-of-formaldehyde** [jchv/deadbeef-vgmstream#3]
No other description for the issue, sadly since the plugin randomly broke.

**Comment by jchv** [comment]
Are you sure you are posting this to the correct project? This project integrates VGMStream with Deadbeef, providing support for streamed music formats like ADX. libvgm is a library that provides chiptune playback support. I don't think this plugin should require libvgm at all.

**Comment by dreams-of-formaldehyde** [comment]
My bad, so in an explanation of what really happened was that something happened to my vgm.so, causing it not to load at all. I cannot track the cause down but it is fixed after a recompilation.
